// GENERATED by server/train_brain.py - do not edit by hand.
//
// THE ENTIRE ENEMY DECISION POLICY:
//   40 int8 move weights + 2 int8 shoot weights + 1 f32 scale
//   = 46 bytes  (that's the whole "AI", derived in closed form)
//
// features: bias, far, tent_hi, tent_lo, hurt, danger, pweak, sideC

export interface TinyBrainData {
    classes: string[];
    features: string[];
    weights: number[];   // 5 x 8, row-major
    shoot: number[];     // [bias, far]
    scale: number;
    temp: number;
    gain: number;
    jitter: number;
    agreement: number;
    max_prob_error: number;
    calibration_drift: number;
    shoot_mae: number;
    bytes: number;
}

export const TINY_BRAIN: TinyBrainData = {
    classes: ["adv", "strf", "flk_l", "flk_r", "ret"],
    features: ["bias", "far", "tent_hi", "tent_lo", "hurt", "danger", "pweak", "sideC"],
    weights: [77,10,-29,29,-44,-32,0,0,30,10,-21,-11,0,36,0,0,12,10,5,-5,0,-16,0,-13,12,10,5,-5,0,-16,0,13,-34,-11,6,-6,127,32,24,0],
    shoot: [36,-26],
    scale: 0.02519685,
    temp: 0.45,
    gain: 1.6,
    jitter: 0.05,
    agreement: 0.995,
    max_prob_error: 0.01228,
    calibration_drift: 0.0,
    shoot_mae: 0.00371,
    bytes: 46
};
